# Stages
# Stage-1:
  # Task-1: Build Docker Image and push to Azure Container Registry ACR
  # Task-2: Copy kube-manifest files to Build Artifact Directory
  # Task-3: Publish build articats to Azure Pipelines
# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  


trigger:
- master

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build job
        pool:
          vmImage: "ubuntu-latest"
        steps:
        # Task-1: Build Docker Image and push to Azure Container Registry ACR
        - task: Docker@2
          inputs:
            containerRegistry: 'acr-service-connection'
            repository: 'custom2-nginx'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: $(Build.sourceVersion)
        # Task-2: Copy kube-manifest files to Build Artifact Directory
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/Azure-DevOps-with-AKS/1-Azure-DevOps-BuildandPush-to-ACR/Git-Repository-files/kube-manifests'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)'
        # Task-3: Publish build articats to Azure Pipelines
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'kube-manifests'
            publishLocation: 'Container'
